"""create attachments table

Revision ID: 03b154e948e4
Revises: 
Create Date: 2026-08-27 16:38:57.377287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b154e948e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.String(length=255), nullable=True),
    sa.Column('context_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'stored', name='statusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_context', 'attachments', ['context_type', 'context_id'], unique=False)
    op.create_index(op.f('ix_attachments_owner_id'), 'attachments', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_owner_id'), table_name='attachments')
    op.drop_index('ix_attachments_context', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
