"""drop unused context_type and context_id from attachments

Revision ID: 477cbe2ee3df
Revises: 03b154e948e4
Create Date: 2026-09-23 06:18:22.566644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477cbe2ee3df'
down_revision: Union[str, Sequence[str], None] = '03b154e948e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_context'), table_name='attachments')
    op.drop_column('attachments', 'context_id')
    op.drop_column('attachments', 'context_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('context_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('context_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_attachments_context'), 'attachments', ['context_type', 'context_id'], unique=False)
    # ### end Alembic commands ###
